apiVersion: v1
kind: Namespace
metadata:
  name: vaultls
  labels:
    name: vaultls
    app.kubernetes.io/name: vaultls
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: vaultls
    app.kubernetes.io/managed-by: kubectl
  annotations:
    description: "VaulTLS Certificate Management Platform"
    contact: "admin@vaultls.com"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: vaultls-quota
  namespace: vaultls
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: vaultls-limits
  namespace: vaultls
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "2"
      memory: "4Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container
