name: Build and Push Container Image on Release

on:
  release:
    types: [published]
  workflow_dispatch: # manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract release tag
      id: get_tag
      run: echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Set lowercase repository name and release tag
      run: |
        echo "REPO_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        file: ./Containerfile
        push: true
        tags: |
          ghcr.io/${{ env.REPO_LOWER }}:${{ env.RELEASE_TAG }}
          ghcr.io/${{ env.REPO_LOWER }}:latest
