name: Push Latest Tag

on:
  workflow_dispatch: # manual trigger

jobs:
  push-latest:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set lowercase repository name and release tag
        run: |
          echo "REPO_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Pull existing versioned image
        run: docker pull ghcr.io/${{ env.REPO_LOWER }}:v0.5.0

      - name: Tag as latest
        run: docker tag ghcr.io/${{ env.REPO_LOWER }}:v0.5.0 ghcr.io/${{ env.REPO_LOWER }}:latest

      - name: Push latest tag
        run: docker push ghcr.io/${{ env.REPO_LOWER }}:latest
