name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # NPM cache
      - name: Cache NPM
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Cargo registry cache
      - name: Cache Cargo Registry
        uses: actions/cache@v4
        with:
          path: /tmp/cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      # Cargo git cache
      - name: Cache Cargo Git
        uses: actions/cache@v4
        with:
          path: /tmp/cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-

      # Cargo target build cache
      - name: Cache Cargo Target
        uses: actions/cache@v4
        with:
          path: /tmp/target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-

      # Docker Buildx layer cache
      - name: Cache Docker Layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Containerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build Docker Image with Cache
        run: |
          docker buildx create --use
          docker buildx build \
            --file Containerfile.github \
            --tag vaultls:test \
            --load \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache \
            --build-arg CARGO_REGISTRY_CACHE=/tmp/cargo/registry \
            --build-arg CARGO_GIT_CACHE=/tmp/cargo/git \
            --build-arg CARGO_TARGET_DIR=/tmp/target \
            .

      - name: Run E2E Tests
        working-directory: ./tests
        run: docker-compose up --abort-on-container-exit --exit-code-from test
