name: Test VaulTLS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Clippy
        working-directory: ./backend
        run: rustup component add clippy
      - name: Build
        working-directory: ./backend
        run: cargo build --verbose
      - name: Run Clippy (deny warnings)
        working-directory: ./backend
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run Tests
        working-directory: ./backend
        run: cargo test --all